### ISSUE TITLE
pnpm install on windows 10 not working

### ISSUE THREAD

**Issue by nigelp** [coleam00/bolt.new-any-llm#148]
### Describe the bug

the pnpm install is failing. Git clone works fine. But when I try to pnpm "x" the error is:
 ENOENT  ENOENT: no such file or directory, mkdir '\\?'

pnpm: ENOENT: no such file or directory, mkdir '\\?'
    at async Object.mkdir (node:internal/fs/promises:858:10)
    at async createNewStoreController (C:\Users\User\AppData\Roaming\npm\node_modules\pnpm\dist\pnpm.cjs:135676:7)
    at async installDeps (C:\Users\User\AppData\Roaming\npm\node_modules\pnpm\dist\pnpm.cjs:198634:21)
    at async C:\Users\User\AppData\Roaming\npm\node_modules\pnpm\dist\pnpm.cjs:234722:21
    at async main (C:\Users\User\AppData\Roaming\npm\node_modules\pnpm\dist\pnpm.cjs:234681:34)
    at async runPnpm (C:\Users\User\AppData\Roaming\npm\node_modules\pnpm\dist\pnpm.cjs:234953:5)
    at async C:\Users\User\AppData\Roaming\npm\node_modules\pnpm\dist\pnpm.cjs:234945:7

### Link to the Bolt URL that caused the error

D:\boltcole\bolt.new-any-llm

### Steps to reproduce

1. do git clone
2. cd bolt.new-any-llm
3. pnpm install
4. error

### Expected behavior

I would expect it to install the dependencies

### Platform

- OS: windows
- Version: 10
- Librefox browser (Firefox clone)

**Comment by witzulu** [comment]
Did you install npm on widows you must install it before installing pnpm

This will install node.js and npm
`https://nodejs.org/en/download/package-manager`
(make sure to select windows, or if you don't trust links,i understand, search node.js windows install)
then run
`npm install -g pnpm`
in powershell

**Comment by nigelp** [comment]
Hi Sean, thanks for your response. Yes I have node, npm etc all installed. I also installed pnpm. Very frustrating.

**Comment by witzulu** [comment]
just a shot in the dark.
are you using powershell and is it in administrator mode?
if you open visual studio code in admin mode you can use the terminal also

**Comment by witzulu** [comment]
Sorry for double post. looked around and found this:

**How to solve npm ERR! enoent This is related to npm not being able to find a file**
[https://sebhastian.com/npm-err-enoent/](url)
you can try it maybe you get lucky

**Comment by nigelp** [comment]
Thanks again for your help. I ran the problem through o1-preview and it seems that the pnpm is set to "store-dir=E:\pnpm-store".

I don't have an E: drive on my computer, and I have installed pnpm properly. So once I set the store to my local proper location on my C: drive, it all worked fine.

pnpm config set store-dir C:\[correct_user_directory]\.pnpm-store
pnpm config list (to check)

I think there should be an issue created so people don't go through all my hassles because of a sloppy mistake.

**Comment by PBemm69** [comment]
I also had lot of problems and all vanished when I installed Visual c++ latest version. Maybe this could help:

a) Install Visual c++ latest version
b) delete Bolt.new directory
c) Delete all your related sub directories from User folders ====> C:\ User\.......\appdata (this is a hidden sub folder)\local\
from there remove all npm and pnpm directories
d) Then start from the beginning

I am not that technical but this is what I did and it worked for me. I think this will do the job for you as well.

**Comment by cueup** [comment]
@witzulu try: npm i -g pnpm@9.4.0
