### ISSUE TITLE
enhance prompt not working

### ISSUE THREAD

**Issue by twriad969** [coleam00/bolt.new-any-llm#149]
### Describe the bug

**the prompt enhanced button is not works in any llm**

### Link to the Bolt URL that caused the error

http://localhost:5173/

### Steps to reproduce

..

### Expected behavior

..

### Screen Recording / Screenshot

..

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

..

**Comment by nigelp** [comment]
Same here.

**Comment by frogman544** [comment]
Same here. This is what i got from console:

`{"message":"You made a GET request to \"/api/enhancer\" but did not provide a `loader` for route \"routes/api.enhancer\", so there is no way to handle the request.","stack":"Error: You made a GET request to \"/api/enhancer\" but did not provide a `loader` for route \"routes/api.enhancer\", so there is no way to handle the request.\n    at getInternalRouterError (/app/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:5061:59)\n    at loadRouteData (/app/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:3991:13)\n    at queryImpl (/app/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:3861:26)\n    at Object.queryRoute (/app/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:3827:24)\n    at handleResourceRequest (/app/node_modules/.pnpm/@remix-run+server-runtime@2.10.0_typescript@5.5.2/node_modules/@remix-run/server-runtime/dist/server.js:413:40)\n    at requestHandler (/app/node_modules/.pnpm/@remix-run+server-runtime@2.10.0_typescript@5.5.2/node_modules/@remix-run/server-runtime/dist/server.js:156:24)\n    at /app/node_modules/.pnpm/@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge/node_modules/@remix-run/dev/dist/vite/cloudflare-proxy-plugin.js:70:31\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}`

**Comment by SujalXplores** [comment]
Fixed this issue in #347

**Comment by aliasfoxkde** [comment]
Same. Mine functions but doesn't work.
