### ISSUE TITLE
not creating the file and code in the editor and not saving the chat. 

### ISSUE THREAD

**Issue by Archviz360** [coleam00/bolt.new-any-llm#153]
I have a few problem. 

1. when requesting to create asimple web app it writes down the code in the chat but not making the main files as it should do. 

2. it doesnt save chat history 

![Problem 1](https://github.com/user-attachments/assets/2f761c66-5a81-47a9-941f-c1f63965a3ff)
![Problem 2](https://github.com/user-attachments/assets/b8e2eafa-a853-488e-8044-86d693c6884f)

Here are pictures that shows what my problem is.

**Comment by Archviz360** [comment]
here are terminal out put: 
LoadAPIKeyError [AI_LoadAPIKeyError]: Anthropic API key is missing. Pass it using the 'apiKey' parameter or the ANTHROPIC_API_KEY environment variable.
    at loadApiKey (file:///C:/Users/dacia/bolt.new-any-llm/node_modules/.pnpm/@ai-sdk+provider-utils@1.0.9_zod@3.23.8/node_modules/@ai-sdk/provider-utils/dist/index.mjs:99:11)
    at Object.getHeaders [as headers] (file:///C:/Users/dacia/bolt.new-any-llm/node_modules/.pnpm/@ai-sdk+anthropic@0.0.39_zod@3.23.8/node_modules/@ai-sdk/anthropic/dist/index.mjs:655:18)
    at AnthropicMessagesLanguageModel.doStream (file:///C:/Users/dacia/bolt.new-any-llm/node_modules/.pnpm/@ai-sdk+anthropic@0.0.39_zod@3.23.8/node_modules/@ai-sdk/anthropic/dist/index.mjs:359:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fn (file:///C:/Users/dacia/bolt.new-any-llm/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/dist/index.mjs:3938:23)
    at async file:///C:/Users/dacia/bolt.new-any-llm/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/dist/index.mjs:256:22
    at async _retryWithExponentialBackoff (file:///C:/Users/dacia/bolt.new-any-llm/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/dist/index.mjs:86:12) {
  cause: undefined,
  [Symbol(vercel.ai.error)]: true,
  [Symbol(vercel.ai.error.AI_LoadAPIKeyError)]: true
  
  the model im using is [ollama ](codellama:7b) 
  its locally via ollama server

**Comment by khalidmaquilang** [comment]
same

**Comment by sardonivictus** [comment]
I have the same issue, using ollama with gwen2.5 14b. It'll happily spew code at me but not interact with the code editor bit making files and whatnot.

**Comment by khalidmaquilang** [comment]
> I have the same issue, using ollama with gwen2.5 14b. It'll happily spew code at me but not interact with the code editor bit making files and whatnot. I will try again in a bit using the openai like api base url and some other models to see if I get a different result.

nice.. mine returns an error

**Comment by Archviz360** [comment]
ca nany one help me?

**Comment by ElG0hary** [comment]
Same here, managed to solve error problem but not code geneative not interacting with editor

**Comment by the0ckid82** [comment]
some what of a work around that works "most of the time" start your project and after you submit your first message stop it right away. click the code button to open the editor and then resubmit your first message. Cole mentioned this in one of his YT videos  [Cole mentioned this in one of his YT videos](https://youtu.be/p1YvKuRfEhg?t=761)

**Comment by ElG0hary** [comment]
### Solved:
Create a file name Modelfile (no file extension)
then open it with notepad and paste this:

FROM llama3.2:latest
PARAMETER num_ctx 32768

change only the model name as what u are using.
after that open cmd
and use this command
ollama create -f Modelfile bolt.new-Ollama
Note: bolt.new-Ollama is the new model you are gonna choose when using it with your locale Bolt.new so dont choose regular ollama 3.2b

Reason for not working to begin with: Difference between Context window between ollama and other models.

**Comment by Archviz360** [comment]
i fixed it. here are how to fix it 

step 1. first create modfile remember to not have any extention after the mod file. 

step 2 in the modfile use following lines 
FROM [qwen2.5-coder:7b]
PARAMETER num_ctx 32768

step 3 in terminal use following line 
ollama create -f Modelfile [qwen2.5-coder-extra-ctx:7b]
after that you will get a message in terminal that says its acepted and received. 

step 4 open bolt on localhost and make sure it uses the modded model in this case it will be qwen2.5-coder:latest(7.6B) 

required Model is qwen 2.5. You can get it from here 
https://ollama.com/library/qwen2.5

i also recomend to create the modfile in the folder of ollama model and use terinal there aswell. Let me know if you got it to work

**Comment by mbraeuner** [comment]
> ### Solved:
> 
> Create a file name Modelfile (no file extension) then open it with notepad and paste this:
> 
> FROM llama3.2:latest PARAMETER num_ctx 32768

Thanks a lot! This works for me. I tried with codelama and llama3
But it works only if I click the demo Links on starting page. If I type "Build a todo app in React using Tailwin" I will get an step by step guide without writing code. Then I have to stop and resend request "Build a todo app in React using Tailwin" it works.

I'm trying to reproduce, but sometimes the file creation does not work properly even if I stop the first prompt

**Comment by praful-dhabekar** [comment]
> step 2 in the modfile use following lines

I think you misspelled here it is Modelfile

> step 3 in terminal use following line ollama create -f Modelfile [qwen2.5-coder-extra-ctx:7b] after that you will get a message in terminal that says its acepted and received.

I have tried above steps and got below error:
`E:\Projects\bolt.new-any-llm>ollama create -f Modelfile [qwen2.5:7b]
transferring model data
Error: invalid model name`

When I tried without the bracket it succeeded but didn't work in the chat. Still getting the single response.

`E:\Projects\bolt.new-any-llm>ollama create -f Modelfile qwen2.5:7b
transferring model data
using existing layer sha256:2bada8a7450677000f678be90653b85d364de7db25eb5ea54136ada5f3933730
using existing layer sha256:66b9ea09bd5b7099cbb4fc820f31b575c0366fa439b08245566692c6784e281e
using existing layer sha256:eb4402837c7829a690fa845de4d7f3fd842c2adee476d5341da8a46ea9255175
using existing layer sha256:832dd9e00a68dd83b3c3fb9f5588dad7dcf337a0db50f7d9483f310cd292e92e
creating new layer sha256:db8fbfd0cb288a053f83ac9014ca9bac2558b1bbcd80b5c408a548e7acba8a24
creating new layer sha256:9afbaf7492e8f000d1af51b9b53c605716af7674e9ca86edb82af366bdd911c6
writing manifest
success`

**Comment by mbraeuner** [comment]
> FROM [qwen2.5-coder:7b]
> PARAMETER num_ctx 32768

without brackets:
```
FROM qwen2.5-coder:7b
PARAMETER num_ctx 32768
```
I'm not sure if it works with the old model name. I used the advice from [ElG0harys comment](https://github.com/coleam00/bolt.new-any-llm/issues/153#issuecomment-2453450985) and used a new model name
ollama create -f Modelfile <here_a_**new**_model_name>
for example:
`ollama create -f Modelfile bolt.qwen2.5-coder:7b`
