### ISSUE TITLE
Windows Project Run Issues

### ISSUE THREAD

**Issue by Ridoy302583** [coleam00/bolt.new-any-llm#174]
### Describe the bug

When I type pnpm run dev or pnpm run preview then i got this error
C:\Users\user\bolt.new-any-llm>pnpm run preview

> bolt@ preview C:\Users\user\bolt.new-any-llm
> pnpm run build && pnpm run start

> bolt@ build C:\Users\user\bolt.new-any-llm
> remix vite:build

*** Received structured exception #0xc0000005: access violation; stack: 7ff9a6622f57 7ff7ebdd337b 7ff7ebdd3443 7ff7ebdc74bc 7ff7ebdc7467 7ff7eb647d5e 7ff7eb64806f 7ff7ea531706 7ff7ea5314ea 7ff7eb7bf97f 7ff7eb7c6b36 7ff7eb7bfe9c 7ff7eb7c6b36 7ff7eb7bd80c 7ff7ea521551 7ff7ecea8bff 7ff9cef7257c 7ff9d0fcaf07
MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
    at #assembleAndUpdateConfig (C:\Users\user\bolt.new-any-llm\node_modules\.pnpm\miniflare@3.20240701.0\node_modules\miniflare\dist\src\index.js:9178:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Mutex.runWith (C:\Users\user\bolt.new-any-llm\node_modules\.pnpm\miniflare@3.20240701.0\node_modules\miniflare\dist\src\index.js:3521:16)
    at async #waitForReady (C:\Users\user\bolt.new-any-llm\node_modules\.pnpm\miniflare@3.20240701.0\node_modules\miniflare\dist\src\index.js:9235:5)
    at async Miniflare2._getProxyClient (C:\Users\user\bolt.new-any-llm\node_modules\.pnpm\miniflare@3.20240701.0\node_modules\miniflare\dist\src\index.js:9359:5)
    at async Miniflare2.getBindings (C:\Users\user\bolt.new-any-llm\node_modules\.pnpm\miniflare@3.20240701.0\node_modules\miniflare\dist\src\index.js:9378:25)
    at async getPlatformProxy (C:\Users\user\bolt.new-any-llm\node_modules\.pnpm\wrangler@3.63.2_@cloudflare+workers-types@4.20240620.0\node_modules\wrangler\wrangler-dist\cli.js:210522:20)
    at async configureServer (C:\Users\user\bolt.new-any-llm\node_modules\.pnpm\@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge\node_modules\@remix-run\dev\dist\vite\cloudflare-proxy-plugin.js:55:11)
    at async _createServer (file:///C:/Users/user/bolt.new-any-llm/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:63299:20)
    at async configResolved (C:\Users\user\bolt.new-any-llm\node_modules\.pnpm\@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge\node_modules\@remix-run\dev\dist\vite\plugin.js:750:27)
    at async Promise.all (index 4)
    at async Module.resolveConfig (file:///C:/Users/user/bolt.new-any-llm/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:66626:3)
    at async Object.resolveViteConfig (C:\Users\user\bolt.new-any-llm\node_modules\.pnpm\@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge\node_modules\@remix-run\dev\dist\vite\plugin.js:71:20)
    at async build (C:\Users\user\bolt.new-any-llm\node_modules\.pnpm\@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge\node_modules\@remix-run\dev\dist\vite\build.js:192:20)
    at async Object.viteBuild (C:\Users\user\bolt.new-any-llm\node_modules\.pnpm\@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge\node_modules\@remix-run\dev\dist\cli\commands.js:183:5)
    at async Object.run (C:\Users\user\bolt.new-any-llm\node_modules\.pnpm\@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge\node_modules\@remix-run\dev\dist\cli\run.js:252:7) {
  code: 'ERR_RUNTIME_FAILURE',
  cause: undefined
}
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.

### Link to the Bolt URL that caused the error

www.bolt.new

### Steps to reproduce

When I type pnpm run dev or pnpm run preview then i got this error
C:\Users\user\bolt.new-any-llm>pnpm run preview

> bolt@ preview C:\Users\user\bolt.new-any-llm
> pnpm run build && pnpm run start

> bolt@ build C:\Users\user\bolt.new-any-llm
> remix vite:build

*** Received structured exception #0xc0000005: access violation; stack: 7ff9a6622f57 7ff7ebdd337b 7ff7ebdd3443 7ff7ebdc74bc 7ff7ebdc7467 7ff7eb647d5e 7ff7eb64806f 7ff7ea531706 7ff7ea5314ea 7ff7eb7bf97f 7ff7eb7c6b36 7ff7eb7bfe9c 7ff7eb7c6b36 7ff7eb7bd80c 7ff7ea521551 7ff7ecea8bff 7ff9cef7257c 7ff9d0fcaf07
MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
    at #assembleAndUpdateConfig (C:\Users\user\bolt.new-any-llm\node_modules\.pnpm\miniflare@3.20240701.0\node_modules\miniflare\dist\src\index.js:9178:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Mutex.runWith (C:\Users\user\bolt.new-any-llm\node_modules\.pnpm\miniflare@3.20240701.0\node_modules\miniflare\dist\src\index.js:3521:16)
    at async #waitForReady (C:\Users\user\bolt.new-any-llm\node_modules\.pnpm\miniflare@3.20240701.0\node_modules\miniflare\dist\src\index.js:9235:5)
    at async Miniflare2._getProxyClient (C:\Users\user\bolt.new-any-llm\node_modules\.pnpm\miniflare@3.20240701.0\node_modules\miniflare\dist\src\index.js:9359:5)
    at async Miniflare2.getBindings (C:\Users\user\bolt.new-any-llm\node_modules\.pnpm\miniflare@3.20240701.0\node_modules\miniflare\dist\src\index.js:9378:25)
    at async getPlatformProxy (C:\Users\user\bolt.new-any-llm\node_modules\.pnpm\wrangler@3.63.2_@cloudflare+workers-types@4.20240620.0\node_modules\wrangler\wrangler-dist\cli.js:210522:20)
    at async configureServer (C:\Users\user\bolt.new-any-llm\node_modules\.pnpm\@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge\node_modules\@remix-run\dev\dist\vite\cloudflare-proxy-plugin.js:55:11)
    at async _createServer (file:///C:/Users/user/bolt.new-any-llm/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:63299:20)
    at async configResolved (C:\Users\user\bolt.new-any-llm\node_modules\.pnpm\@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge\node_modules\@remix-run\dev\dist\vite\plugin.js:750:27)
    at async Promise.all (index 4)
    at async Module.resolveConfig (file:///C:/Users/user/bolt.new-any-llm/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:66626:3)
    at async Object.resolveViteConfig (C:\Users\user\bolt.new-any-llm\node_modules\.pnpm\@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge\node_modules\@remix-run\dev\dist\vite\plugin.js:71:20)
    at async build (C:\Users\user\bolt.new-any-llm\node_modules\.pnpm\@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge\node_modules\@remix-run\dev\dist\vite\build.js:192:20)
    at async Object.viteBuild (C:\Users\user\bolt.new-any-llm\node_modules\.pnpm\@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge\node_modules\@remix-run\dev\dist\cli\commands.js:183:5)
    at async Object.run (C:\Users\user\bolt.new-any-llm\node_modules\.pnpm\@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge\node_modules\@remix-run\dev\dist\cli\run.js:252:7) {
  code: 'ERR_RUNTIME_FAILURE',
  cause: undefined
}
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.

### Expected behavior

Show localhost..

### Platform

- OS: Windows-11

**Comment by Prodipds** [comment]
Same issue for me as well
While "pnpm run dev" getting this error.

*** Received structured exception #0xc0000005: access violation; stack: 7ffaf299301f 7ff6c72b337b 7ff6c72b3443 7ff6c72a74bc 7ff6c72a7467 7ff6c6b27d5e 7ff6c6b2806f 7ff6c5a11706 7ff6c5a114ea 7ff6c6c9f97f 7ff6c6ca6b36 7ff6c6c9fe9c 7ff6c6ca6b36 7ff6c6c9d80c 7ff6c5a01551 7ff6c8388bff 7ffb09f57373 7ffb0bcbcc90
MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
    at #assembleAndUpdateConfig (C:\Users\Pro\bolt.new-any-llm\node_modules\.pnpm\miniflare@3.20240701.0\node_modules\miniflare\dist\src\index.js:9178:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Mutex.runWith (C:\Users\Pro\bolt.new-any-llm\node_modules\.pnpm\miniflare@3.20240701.0\node_modules\miniflare\dist\src\index.js:3521:16)
    at async #waitForReady (C:\Users\Pro\bolt.new-any-llm\node_modules\.pnpm\miniflare@3.20240701.0\node_modules\miniflare\dist\src\index.js:9235:5)
    at async Miniflare2._getProxyClient (C:\Users\Pro\bolt.new-any-llm\node_modules\.pnpm\miniflare@3.20240701.0\node_modules\miniflare\dist\src\index.js:9359:5)
    at async Miniflare2.getBindings (C:\Users\Pro\bolt.new-any-llm\node_modules\.pnpm\miniflare@3.20240701.0\node_modules\miniflare\dist\src\index.js:9378:25)
    at async getPlatformProxy (C:\Users\Pro\bolt.new-any-llm\nodemodules\.pnpm\wrangler@3.63.2@cloudflare+workers-types@4.20240620.0\node_modules\wrangler\wrangler-dist\cli.js:210522:20)
    at async configureServer (C:\Users\Pro\bolt.new-any-llm\nodemodules\.pnpm\@remix-run+dev@2.10.0@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge\nodemodules\@remix-run\dev\dist\vite\cloudflare-proxy-plugin.js:55:11)
    at async createServer (file:///C:/Users/Pro/bolt.new-any-llm/nodemodules/.pnpm/vite@5.3.1@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:63299:20)
    at async configResolved (C:\Users\Pro\bolt.new-any-llm\nodemodules\.pnpm\@remix-run+dev@2.10.0@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge\node_modules\@remix-run\dev\dist\vite\plugin.js:750:27)
    at async Promise.all (index 3)
    at async resolveConfig (file:///C:/Users/Pro/bolt.new-any-llm/nodemodules/.pnpm/vite@5.3.1@types+node@20.14.9_sass@1.77.6/nodemodules/vite/dist/node/chunks/dep-BcXSligG.js:66626:3)
    at async createServer (file:///C:/Users/Pro/bolt.new-any-llm/nodemodules/.pnpm/vite@5.3.1@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:62977:18)
    at async dev (C:\Users\Pro\bolt.new-any-llm\nodemodules\.pnpm\@remix-run+dev@2.10.0@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge\node_modules\@remix-run\dev\dist\vite\dev.js:39:16)
    at async Object.viteDev (C:\Users\Pro\bolt.new-any-llm\nodemodules\.pnpm\@remix-run+dev@2.10.0@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge\node_modules\@remix-run\dev\dist\cli\commands.js:220:3)
    at async Object.run (C:\Users\Pro\bolt.new-any-llm\nodemodules\.pnpm\@remix-run+dev@2.10.0@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge\node_modules\@remix-run\dev\dist\cli\run.js:271:7) {
  code: 'ERR_RUNTIME_FAILURE',
  cause: undefined
}
 ELIFECYCLE  Command failed with exit code 1.

**Comment by aliasfoxkde** [comment]
Sounds like a version compatibility issue with node.

I'd start by updating your node version with `npm install -g npm@latest`

If that doesn't work maybe try deleting the "node_modules" and lock file, cleaning things up, and re-running dev:
```
pnpm install
pnpm run clean
pnpm run dev
```

You also may want to re-install pnpm with `npm install pnpm`.
