### ISSUE TITLE
 .env.local not being passed

### ISSUE THREAD

**Issue by turbra** [coleam00/bolt.new-any-llm#221]
### Describe the bug

.env.local is not being passed which leads to missing api keys

### Link to the Bolt URL that caused the error

n/a

### Steps to reproduce

 `podman-compose --env-file ./.env.local up -d`

```bash
➜ podman logs -f boltnew-any-llm_bolt-ai_1

> bolt@ dockerstart /app
> bindings=$(./bindings.sh) && wrangler pages dev ./build/client $bindings --ip 0.0.0.0 --port 5173 --no-show-interactive-dev-session

./bindings.sh: line 12: .env.local: No such file or directory

 ⛅️ wrangler 3.63.2 (update available 3.86.0)
---------------------------------------------

✨ Compiled Worker successfully
[wrangler:inf] Ready on http://0.0.0.0:5173
[wrangler:inf] - http://127.0.0.1:5173
[wrangler:inf] - http://10.89.13.68:5173
⎔ Starting local server...
[wrangler:inf] GET /chat/react-todo-app-4 200 OK (136ms)
[wrangler:inf] GET /assets/ReactToastify-CYivYX3d.css 200 OK (22ms)
[wrangler:inf] GET /assets/root-BAISjcDY.css 200 OK (22ms)
[wrangler:inf] GET /assets/entry.client-ydwSl9ol.js 200 OK (189ms)
[wrangler:inf] GET /assets/tailwind-compat-CC20SAMN.css 200 OK (206ms)
[wrangler:inf] GET /assets/index-CPTzpSUP.css 200 OK (205ms)
[wrangler:inf] GET /assets/root-CTO1zTZC.js 200 OK (190ms)
[wrangler:inf] GET /assets/xterm-lQO2bNqs.css 200 OK (206ms)
[wrangler:inf] GET /assets/manifest-5c4a8c33.js 200 OK (206ms)
[wrangler:inf] GET /assets/_index-D_NZK3VS.css 200 OK (208ms)
[wrangler:inf] GET /assets/components-bNrEeZYQ.js 200 OK (195ms)
[wrangler:inf] GET /assets/_index-gsG53wsF.js 200 OK (197ms)
[wrangler:inf] GET /assets/chat._id-ByV4U8O5.js 200 OK (205ms)
[wrangler:inf] GET /assets/theme-C4y9B7zS.js 200 OK (205ms)
[wrangler:inf] GET /assets/dark-plus-KEYLhlmT.js 200 OK (8ms)
[wrangler:inf] GET /assets/wasm-CsTmP73Z.js 200 OK (24ms)
[wrangler:inf] GET /assets/light-plus-BsvsQ1iS.js 200 OK (12ms)
[wrangler:inf] GET /assets/shellscript-BZfs-ost.js 200 OK (18ms)
[wrangler:inf] GET /assets/_index-C7e2Lv08.js 200 OK (12ms)
[wrangler:inf] GET / 200 OK (13ms)
[wrangler:inf] GET /favicon.svg 200 OK (5ms)
LoadAPIKeyError [AI_LoadAPIKeyError]: OpenAI API key is missing. Pass it using the 'apiKey' parameter. Environment variables is not supported in this environment.
    at loadApiKey (file:///app/node_modules/.pnpm/@ai-sdk+provider-utils@1.0.20_zod@3.23.8/node_modules/@ai-sdk/provider-utils/src/load-api-key.ts:25:11)
    at Object.getHeaders [as headers] (file:///app/node_modules/.pnpm/@ai-sdk+openai@0.0.66_zod@3.23.8/node_modules/@ai-sdk/openai/src/openai-provider.ts:145:30)
    at OpenAIChatLanguageModel.doStream (file:///app/node_modules/.pnpm/@ai-sdk+openai@0.0.66_zod@3.23.8/node_modules/@ai-sdk/openai/src/openai-chat-language-model.ts:391:43)
    at fn (file:///app/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/core/generate-text/stream-text.ts:345:35)
    at null.<anonymous> (file:///app/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/core/telemetry/record-span.ts:18:28)
    at Object.startActiveSpan (file:///app/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/core/telemetry/noop-tracer.ts:21:14)
    at recordSpan (file:///app/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/core/telemetry/record-span.ts:16:17)
    at null.<anonymous> (file:///app/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/core/generate-text/stream-text.ts:311:11)
    at _retryWithExponentialBackoff (file:///app/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/util/retry-with-exponential-backoff.ts:37:18)
    at null.<anonymous> (file:///app/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/util/retry-with-exponential-backoff.ts:21:5) {
  cause: undefined,
  [Symbol(vercel.ai.error)]: true,
  [Symbol(vercel.ai.error.AI_LoadAPIKeyError)]: true
}
[wrangler:inf] POST /api/chat 500 Internal Server Error (12ms)
```

### Expected behavior

variables are populated in the container

### Platform

- OS: Fedora release 38
- Browser: Chrome, Firefox, Edge

### Additional context

build log we can see the OPEN_AI_KEY has been populated but I have redacted it...
```bash
[2/2] COMMIT bolt-ai:production
--> b23ba2d78146
Successfully tagged localhost/bolt-ai:production
b23ba2d781464eee019a7e09b103094e2aef76a10a756588bbfc8e94cfc08845
exit code: 0
['podman', 'ps', '--filter', 'label=io.podman.compose.project=boltnew-any-llm', '-a', '--format', '{{ index .Labels "io.podman.compose.config-hash"}}']
['podman', 'network', 'exists', 'boltnew-any-llm_default']
podman run --name=boltnew-any-llm_bolt-ai_1 -d --label io.podman.compose.config-hash=10e116225fddc47eea16904ccf0fd0e2b9c8ba28ea14a9ef8f8bb27954c9dfcc --label io.podman.compose.project=boltnew-any-llm --label io.podman.compose.version=1.0.6 --label PODMAN_SYSTEMD_UNIT=podman-compose@boltnew-any-llm.service --label com.docker.compose.project=boltnew-any-llm --label com.docker.compose.project.working_dir=/home/turbra/compose-projects/bolt.new-any-llm --label com.docker.compose.project.config_files=docker-compose.yaml --label com.docker.compose.container-number=1 --label com.docker.compose.service=bolt-ai --env-file /home/turbra/compose-projects/bolt.new-any-llm/.env.local -e NODE_ENV=production -e PORT=5173 -e GROQ_API_KEY= -e OPENAI_API_KEY=<REDACTED> -e ANTHROPIC_API_KEY= -e OPEN_ROUTER_API_KEY= -e GOOGLE_GENERATIVE_AI_API_KEY= -e OLLAMA_API_BASE_URL= -e VITE_LOG_LEVEL=debug -e RUNNING_IN_DOCKER=true --net boltnew-any-llm_default --network-alias bolt-ai --add-host host.docker.internal:host-gateway -p 5173:5173 bolt-ai:production pnpm run dockerstart
399b774799c9c3794fbcd9dc54c5e0343db2b4bc8131b603562d4105c87e3b46
```

pod log showing the OPENAI_API_KEY as well...
```bash
podman exec -it boltnew-any-llm_bolt-ai_1 /bin/bash
root@399b774799c9:/app# env
VITE_LOG_LEVEL=debug
ANTHROPIC_API_KEY=
WRANGLER_SEND_METRICS=false
OPENAI_API_KEY=<REDACTED>
...
```

---
`Dockerfile`
```Dockerfile
ARG BASE=node:20.18.0
FROM ${BASE} AS base

WORKDIR /app

# Install dependencies (this step is cached as long as the dependencies don't change)
COPY package.json pnpm-lock.yaml ./

RUN corepack enable pnpm && pnpm install

# Copy the rest of your app's source code
COPY . .

# Expose the port the app runs on
EXPOSE 5173

# Production image
FROM base AS bolt-ai-production

# Define environment variables with default values or let them be overridden
ARG GROQ_API_KEY
ARG OPENAI_API_KEY
ARG ANTHROPIC_API_KEY
ARG OPEN_ROUTER_API_KEY
ARG GOOGLE_GENERATIVE_AI_API_KEY
ARG OLLAMA_API_BASE_URL
ARG VITE_LOG_LEVEL=debug

ENV WRANGLER_SEND_METRICS=false \
    GROQ_API_KEY=${GROQ_API_KEY} \
    OPENAI_API_KEY=${OPENAI_API_KEY} \
    ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY} \
    OPEN_ROUTER_API_KEY=${OPEN_ROUTER_API_KEY} \
    GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY} \
    OLLAMA_API_BASE_URL=${OLLAMA_API_BASE_URL} \
    VITE_LOG_LEVEL=${VITE_LOG_LEVEL}

# Pre-configure wrangler to disable metrics
RUN mkdir -p /root/.config/.wrangler && \
    echo '{"enabled":false}' > /root/.config/.wrangler/metrics.json

RUN npm run build

CMD [ "pnpm", "run", "dockerstart"]
```
---

`docker-compose.yaml`
```yaml
services:
  bolt-ai:
    image: bolt-ai:production
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file: ".env.local"
    environment:
      - NODE_ENV=production
      # No strictly neded but serving as hints for Coolify
      - PORT=5173
      - GROQ_API_KEY=${GROQ_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPEN_ROUTER_API_KEY=${OPEN_ROUTER_API_KEY}
      - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY}
      - OLLAMA_API_BASE_URL=${OLLAMA_API_BASE_URL}
      - VITE_LOG_LEVEL=${VITE_LOG_LEVEL:-debug}
      - RUNNING_IN_DOCKER=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: pnpm run dockerstart
```

The workaround at the moment is to comment out `*.local` from the `.dockerignore`

`.dockerignore`
```Dockerfile
# Ignore Git and GitHub files
.git
.github/

# Ignore Husky configuration files
.husky/

# Ignore documentation and metadata files
CONTRIBUTING.md
LICENSE
README.md

# Ignore environment examples and sensitive info
.env
# *.local <---------- 
*.example

# Ignore node modules, logs and cache files
**/*.log
**/node_modules
**/dist
**/build
**/.cache
logs
dist-ssr
.DS_Store
```

**Comment by turbra** [comment]
Tweaking the `bindings.sh` to use environment variables directly is a decent solution.

`podman-compose --env-file .env.local up -d`

`bindings.sh`
```bash
#!/bin/bash

bindings=""

# List all the environment variables you need
keys=(
  "GROQ_API_KEY"
  "OPENAI_API_KEY"
  "ANTHROPIC_API_KEY"
  "OPEN_ROUTER_API_KEY"
  "GOOGLE_GENERATIVE_AI_API_KEY"
  "OLLAMA_API_BASE_URL"
  "OPENAI_LIKE_API_BASE_URL"
  "DEEPSEEK_API_KEY"
  "OPENAI_LIKE_API_KEY"
  "MISTRAL_API_KEY"
  "XAI_API_KEY"
  "VITE_LOG_LEVEL"
)

# Iterate over each key and retrieve its value from the environment
for key in "${keys[@]}"; do
  value=$(printenv "$key")
  if [[ -n "$value" ]]; then
    bindings+="--binding ${key}=${value} "
  fi
done

# Trim any trailing whitespace
bindings=$(echo $bindings | sed 's/[[:space:]]*$//')

echo $bindings
```

**Comment by coleam00** [comment]
You should also be able to use .env instead of .env.local! I have the instructions updated for that.

**Comment by turbra** [comment]
> You should also be able to use .env instead of .env.local! I have the instructions updated for that.

Using `.env` produces the same `LoadAPIKeyError [AI_LoadAPIKeyError]: OpenAI API key is missing.` even though the container shows it as defined

```bash
podman exec -it boltnew-any-llm_bolt-ai_1 /bin/bash
root@399b774799c9:/app# env
VITE_LOG_LEVEL=debug
ANTHROPIC_API_KEY=
WRANGLER_SEND_METRICS=false
OPENAI_API_KEY=<REDACTED>
```

**Comment by TrailandCamp** [comment]
The .env files are set to no-no in .dockerignore...

**Comment by guntram** [comment]
The .env files are set to no-no in the .dockerignore file.
