### ISSUE TITLE
Issue with Bolt and Ollama

### ISSUE THREAD

**Issue by WhitePine2024** [coleam00/bolt.new-any-llm#410]
### Describe the bug

I have been able to create my local bolt.new and use API keys to connect with the Ai models but the biggest issue is with Ollama and getting this set up. I have been using cursor & chat Gpt to solve it and keep going around in circles. I believe everything is set up properly per the read me. Looking to connect with someone to help get this final set up coming on probably 30 hours of playing with this.  

### Link to the Bolt URL that caused the error

.

### Steps to reproduce

I create my local host site and then try to use it and it does not work. 

### Expected behavior

I get to my local bolt.new on my localhost - I move to ollama and previously i had different versions to choose from but still the end result is the same it would submit questions take a while to do anything and then respond with an error

### Platform

- OS: [Windows 11 Home - x64 based pc
- Browser: . all of these. Chrome, edge, chrome canary]
- Version: of?

This is what I have for Ollama

offic@DESKTOP-VGOJ53N MINGW64 ~/bolt.new-any-llm (main)
$ ollama list

NAME                 ID              SIZE      MODIFIED
qwen-bolt:latest     3a939e242970    4.7 GB    6 hours ago
qwen2.5-coder:7b     2b0496514337    4.7 GB    6 hours ago
codellama:13b        9f438cb9cd58    7.4 GB    7 hours ago
llama2-32k:latest    c24d3c5ee384    3.8 GB    24 hours ago
llama2:latest        78e26419b446    3.8 GB    24 hours ago

### Additional context

trying to get Ollama working with Bolt.new forked version. All the other LLM i set up with API keys work but trying to avoid paying for subscriptions by hosting ollama locally.

**Comment by leex279** [comment]
Are there any Errors in the DEV-Tools-Console (Browser) and/or the shell where you run bolt? Also check the Ollama logfile for errors.

**Comment by cosmx** [comment]
Maybe similar to this issue, I can use OpenAPI but when trying ollama it fails (on MacOS).
Looking at the log I see that the model I choose in the UI is not passed to ollama and instead the claude-3-5-sonnet-latest is passed, therefore ollama replies with error.

Any idea on how to fix this?


Below the log:
```
APICallError [AI_APICallError]: Not Found
    at /Users/cosimo/bolt.new-any-llm/node_modules/.pnpm/@ai-sdk+provider-utils@1.0.20_zod@3.23.8/node_modules/@ai-sdk/provider-utils/dist/index.js:505:14
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async postToApi (/Users/cosimo/bolt.new-any-llm/node_modules/.pnpm/@ai-sdk+provider-utils@1.0.20_zod@3.23.8/node_modules/@ai-sdk/provider-utils/dist/index.js:398:28)
    at async OllamaChatLanguageModel.doStream (/Users/cosimo/bolt.new-any-llm/node_modules/.pnpm/ollama-ai-provider@0.15.2_zod@3.23.8/node_modules/ollama-ai-provider/dist/index.js:485:50)
    at async fn (file:///Users/cosimo/bolt.new-any-llm/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/dist/index.mjs:3938:23)
    at async file:///Users/cosimo/bolt.new-any-llm/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/dist/index.mjs:256:22
    at async _retryWithExponentialBackoff (file:///Users/cosimo/bolt.new-any-llm/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/dist/index.mjs:86:12)
    at async startStep (file:///Users/cosimo/bolt.new-any-llm/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/dist/index.mjs:3903:13)
    at async fn (file:///Users/cosimo/bolt.new-any-llm/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/dist/index.mjs:3977:11)
    at async file:///Users/cosimo/bolt.new-any-llm/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/dist/index.mjs:256:22
    at async chatAction (/Users/cosimo/bolt.new-any-llm/app/routes/api.chat.ts:64:20)
    at async Object.callRouteAction (/Users/cosimo/bolt.new-any-llm/node_modules/.pnpm/@remix-run+server-runtime@2.10.0_typescript@5.5.2/node_modules/@remix-run/server-runtime/dist/data.js:37:16)
    at async /Users/cosimo/bolt.new-any-llm/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:4612:21
    at async callLoaderOrAction (/Users/cosimo/bolt.new-any-llm/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:4677:16)
    at async Promise.all (index 1)
    at async callDataStrategyImpl (/Users/cosimo/bolt.new-any-llm/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:4552:17)
    at async callDataStrategy (/Users/cosimo/bolt.new-any-llm/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:4041:19)
    at async submit (/Users/cosimo/bolt.new-any-llm/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:3900:21)
    at async queryImpl (/Users/cosimo/bolt.new-any-llm/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:3858:22)
    at async Object.queryRoute (/Users/cosimo/bolt.new-any-llm/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:3827:18)
    at async handleResourceRequest (/Users/cosimo/bolt.new-any-llm/node_modules/.pnpm/@remix-run+server-runtime@2.10.0_typescript@5.5.2/node_modules/@remix-run/server-runtime/dist/server.js:413:20)
    at async requestHandler (/Users/cosimo/bolt.new-any-llm/node_modules/.pnpm/@remix-run+server-runtime@2.10.0_typescript@5.5.2/node_modules/@remix-run/server-runtime/dist/server.js:156:18)
    at async /Users/cosimo/bolt.new-any-llm/node_modules/.pnpm/@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge/node_modules/@remix-run/dev/dist/vite/cloudflare-proxy-plugin.js:70:25 {
  cause: undefined,
  url: 'http://localhost:11434/api/chat',
  requestBodyValues: {
    format: undefined,
    model: 'claude-3-5-sonnet-latest',
    options: { num_ctx: 32768, num_predict: 8000, temperature: 0 },
    messages: [ [Object], [Object] ],
    tools: undefined
  },
  statusCode: 404,
  responseHeaders: {
    'content-length': '78',
    'content-type': 'application/json; charset=utf-8',
    date: 'Thu, 28 Nov 2024 22:16:57 GMT'
  },
  responseBody: '{"error":"model \\"claude-3-5-sonnet-latest\\" not found, try pulling it first"}',
  isRetryable: false,
  data: undefined,
  [Symbol(vercel.ai.error)]: true,
  [Symbol(vercel.ai.error.AI_APICallError)]: true
}
```

**Comment by dustinwloring1988** [comment]
it should be fixed now try to update it
