### ISSUE TITLE
ollama not always working after fresh install. Shall a dev/nightly branch be relevant?

### ISSUE THREAD

**Issue by guzdal** [coleam00/bolt.new-any-llm#434]
### Describe the bug

Hi team.
I'm trying to follow the project progression, but it goes without saying everything is getting pretty quick these days. 
Some issues are duplicated to each others and new users like myself, could have a little struggle deploying the whole application right, i.e, using ollama. 

However, Importing project went **closed to just fine!** I successfully imported a 'complex' bolt.new project I was working on, featuring cool React effects. A very pleasant feature you could check on README.md 👍 

So I believe I could ask the main developers **if you intend to create a dev/not so stable branch**? I can see there are a whole lot of new features that are going into the repo and README.md everyday since a couple of weeks, and I'm willing to participate/contribute/donate/write some docs (as I'm no developer, best I can do)

### Link to the Bolt URL that caused the error

localhost:5173

### Steps to reproduce

Removing my oTToDev instance and cleaning it goes as:
```
docker stop <bolt_docker_ID>
docker rm <bolt_docker_ID>
cd .. && rm -fr bolt.new-any-llm/ 
```
Then reinstalling it to go from scratch:
```
git clone https://github.com/coleam00/bolt.new-any-llm.git 
cd bolt.new-any-llm/ 
cp .env.example .env.local
docker build . --target bolt-ai-development 
docker-compose --profile development up   
```
then, going to the local webpage at http://localhost:5173 loads the page successfully, I can reach the Ollama list (I could not on Linux, yesterday and also saw that issue) as you can see here, until this happens whenever I'm testing the chat call: 
<img width="1039" alt="image" src="https://github.com/user-attachments/assets/589d8a55-0f75-44e1-acab-81568aa2c114">

Pasting the console from the main terminal view to catch that API error (whereas I can reach my downloaded ollama models list!) 

```
`bolt-ai-dev-1  | [unocss] failed to load icon "ph:folder-simple-upload"
bolt-ai-dev-1  | APICallError [AI_APICallError]: Not Found
bolt-ai-dev-1  |     at /app/node_modules/.pnpm/@ai-sdk+provider-utils@1.0.20_zod@3.23.8/node_modules/@ai-sdk/provider-utils/dist/index.js:505:14
bolt-ai-dev-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
bolt-ai-dev-1  |     at async postToApi (/app/node_modules/.pnpm/@ai-sdk+provider-utils@1.0.20_zod@3.23.8/node_modules/@ai-sdk/provider-utils/dist/index.js:398:28)
bolt-ai-dev-1  |     at async OllamaChatLanguageModel.doStream (/app/node_modules/.pnpm/ollama-ai-provider@0.15.2_zod@3.23.8/node_modules/ollama-ai-provider/dist/index.js:485:50)
bolt-ai-dev-1  |     at async fn (file:///app/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/dist/index.mjs:3938:23)
bolt-ai-dev-1  |     at async file:///app/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/dist/index.mjs:256:22
bolt-ai-dev-1  |     at async _retryWithExponentialBackoff (file:///app/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/dist/index.mjs:86:12)
bolt-ai-dev-1  |     at async startStep (file:///app/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/dist/index.mjs:3903:13)
bolt-ai-dev-1  |     at async fn (file:///app/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/dist/index.mjs:3977:11)
bolt-ai-dev-1  |     at async file:///app/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/dist/index.mjs:256:22
bolt-ai-dev-1  |     at async chatAction (/app/app/routes/api.chat.ts:64:20)
bolt-ai-dev-1  |     at async Object.callRouteAction (/app/node_modules/.pnpm/@remix-run+server-runtime@2.10.0_typescript@5.5.2/node_modules/@remix-run/server-runtime/dist/data.js:37:16)
bolt-ai-dev-1  |     at async /app/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:4612:21
bolt-ai-dev-1  |     at async callLoaderOrAction (/app/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:4677:16)
bolt-ai-dev-1  |     at async Promise.all (index 1)
bolt-ai-dev-1  |     at async callDataStrategyImpl (/app/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:4552:17)
bolt-ai-dev-1  |     at async callDataStrategy (/app/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:4041:19)
bolt-ai-dev-1  |     at async submit (/app/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:3900:21)
bolt-ai-dev-1  |     at async queryImpl (/app/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:3858:22)
bolt-ai-dev-1  |     at async Object.queryRoute (/app/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:3827:18)
bolt-ai-dev-1  |     at async handleResourceRequest (/app/node_modules/.pnpm/@remix-run+server-runtime@2.10.0_typescript@5.5.2/node_modules/@remix-run/server-runtime/dist/server.js:413:20)
bolt-ai-dev-1  |     at async requestHandler (/app/node_modules/.pnpm/@remix-run+server-runtime@2.10.0_typescript@5.5.2/node_modules/@remix-run/server-runtime/dist/server.js:156:18)
bolt-ai-dev-1  |     at async /app/node_modules/.pnpm/@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge/node_modules/@remix-run/dev/dist/vite/cloudflare-proxy-plugin.js:70:25 {
bolt-ai-dev-1  |   cause: undefined,
bolt-ai-dev-1  |   url: 'http://host.docker.internal:11434/api/chat',
bolt-ai-dev-1  |   requestBodyValues: {
bolt-ai-dev-1  |     format: undefined,
bolt-ai-dev-1  |     model: 'claude-3-5-sonnet-latest',
bolt-ai-dev-1  |     options: { num_ctx: 32768, num_predict: 8000, temperature: 0 },
bolt-ai-dev-1  |     messages: [ [Object], [Object], [Object], [Object] ],
bolt-ai-dev-1  |     tools: undefined
bolt-ai-dev-1  |   },
bolt-ai-dev-1  |   statusCode: 404,
bolt-ai-dev-1  |   responseHeaders: {
bolt-ai-dev-1  |     'content-length': '78',
bolt-ai-dev-1  |     'content-type': 'application/json; charset=utf-8',
bolt-ai-dev-1  |     date: 'Tue, 26 Nov 2024 23:55:09 GMT'
bolt-ai-dev-1  |   },
bolt-ai-dev-1  |   responseBody: '{"error":"model \\"claude-3-5-sonnet-latest\\" not found, try pulling it first"}',
bolt-ai-dev-1  |   isRetryable: false,
bolt-ai-dev-1  |   data: undefined,
bolt-ai-dev-1  |   [Symbol(vercel.ai.error)]: true,
bolt-ai-dev-1  |   [Symbol(vercel.ai.error.AI_APICallError)]: true
bolt-ai-dev-1  | }
bolt-ai-dev-1  | APICallError [AI_APICallError]: Not Found
bolt-ai-dev-1  |     at /app/node_modules/.pnpm/@ai-sdk+provider-utils@1.0.20_zod@3.23.8/node_modules/@ai-sdk/provider-utils/dist/index.js:505:14
bolt-ai-dev-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
bolt-ai-dev-1  |     at async postToApi (/app/node_modules/.pnpm/@ai-sdk+provider-utils@1.0.20_zod@3.23.8/node_modules/@ai-sdk/provider-utils/dist/index.js:398:28)
bolt-ai-dev-1  |     at async OllamaChatLanguageModel.doStream (/app/node_modules/.pnpm/ollama-ai-provider@0.15.2_zod@3.23.8/node_modules/ollama-ai-provider/dist/index.js:485:50)
bolt-ai-dev-1  |     at async fn (file:///app/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/dist/index.mjs:3938:23)
bolt-ai-dev-1  |     at async file:///app/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/dist/index.mjs:256:22
bolt-ai-dev-1  |     at async _retryWithExponentialBackoff (file:///app/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/dist/index.mjs:86:12)
bolt-ai-dev-1  |     at async startStep (file:///app/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/dist/index.mjs:3903:13)
bolt-ai-dev-1  |     at async fn (file:///app/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/dist/index.mjs:3977:11)
bolt-ai-dev-1  |     at async file:///app/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/dist/index.mjs:256:22
bolt-ai-dev-1  |     at async chatAction (/app/app/routes/api.chat.ts:64:20)
bolt-ai-dev-1  |     at async Object.callRouteAction (/app/node_modules/.pnpm/@remix-run+server-runtime@2.10.0_typescript@5.5.2/node_modules/@remix-run/server-runtime/dist/data.js:37:16)
bolt-ai-dev-1  |     at async /app/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:4612:21
bolt-ai-dev-1  |     at async callLoaderOrAction (/app/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:4677:16)
bolt-ai-dev-1  |     at async Promise.all (index 1)
bolt-ai-dev-1  |     at async callDataStrategyImpl (/app/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:4552:17)
bolt-ai-dev-1  |     at async callDataStrategy (/app/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:4041:19)
bolt-ai-dev-1  |     at async submit (/app/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:3900:21)
bolt-ai-dev-1  |     at async queryImpl (/app/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:3858:22)
bolt-ai-dev-1  |     at async Object.queryRoute (/app/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:3827:18)
bolt-ai-dev-1  |     at async handleResourceRequest (/app/node_modules/.pnpm/@remix-run+server-runtime@2.10.0_typescript@5.5.2/node_modules/@remix-run/server-runtime/dist/server.js:413:20)
bolt-ai-dev-1  |     at async requestHandler (/app/node_modules/.pnpm/@remix-run+server-runtime@2.10.0_typescript@5.5.2/node_modules/@remix-run/server-runtime/dist/server.js:156:18)
bolt-ai-dev-1  |     at async /app/node_modules/.pnpm/@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge/node_modules/@remix-run/dev/dist/vite/cloudflare-proxy-plugin.js:70:25 {
bolt-ai-dev-1  |   cause: undefined,
bolt-ai-dev-1  |   url: 'http://host.docker.internal:11434/api/chat',
bolt-ai-dev-1  |   requestBodyValues: {
bolt-ai-dev-1  |     format: undefined,
bolt-ai-dev-1  |     model: 'claude-3-5-sonnet-latest',
bolt-ai-dev-1  |     options: { num_ctx: 32768, num_predict: 8000, temperature: 0 },
bolt-ai-dev-1  |     messages: [ [Object], [Object] ],
bolt-ai-dev-1  |     tools: undefined
bolt-ai-dev-1  |   },
bolt-ai-dev-1  |   statusCode: 404,
bolt-ai-dev-1  |   responseHeaders: {
bolt-ai-dev-1  |     'content-length': '78',
bolt-ai-dev-1  |     'content-type': 'application/json; charset=utf-8',
bolt-ai-dev-1  |     date: 'Tue, 26 Nov 2024 23:55:56 GMT'
bolt-ai-dev-1  |   },
bolt-ai-dev-1  |   responseBody: '{"error":"model \\"claude-3-5-sonnet-latest\\" not found, try pulling it first"}',
bolt-ai-dev-1  |   isRetryable: false,
bolt-ai-dev-1  |   data: undefined,
bolt-ai-dev-1  |   [Symbol(vercel.ai.error)]: true,
bolt-ai-dev-1  |   [Symbol(vercel.ai.error.AI_APICallError)]: true
bolt-ai-dev-1  | }
bolt-ai-dev-1  | APICallError [AI_APICallError]: Not Found
bolt-ai-dev-1  |     at /app/node_modules/.pnpm/@ai-sdk+provider-utils@1.0.20_zod@3.23.8/node_modules/@ai-sdk/provider-utils/dist/index.js:505:14
bolt-ai-dev-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
bolt-ai-dev-1  |     at async postToApi (/app/node_modules/.pnpm/@ai-sdk+provider-utils@1.0.20_zod@3.23.8/node_modules/@ai-sdk/provider-utils/dist/index.js:398:28)
bolt-ai-dev-1  |     at async OllamaChatLanguageModel.doStream (/app/node_modules/.pnpm/ollama-ai-provider@0.15.2_zod@3.23.8/node_modules/ollama-ai-provider/dist/index.js:485:50)
bolt-ai-dev-1  |     at async fn (file:///app/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/dist/index.mjs:3938:23)
bolt-ai-dev-1  |     at async file:///app/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/dist/index.mjs:256:22
bolt-ai-dev-1  |     at async _retryWithExponentialBackoff (file:///app/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/dist/index.mjs:86:12)
bolt-ai-dev-1  |     at async startStep (file:///app/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/dist/index.mjs:3903:13)
bolt-ai-dev-1  |     at async fn (file:///app/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/dist/index.mjs:3977:11)
bolt-ai-dev-1  |     at async file:///app/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/dist/index.mjs:256:22
bolt-ai-dev-1  |     at async chatAction (/app/app/routes/api.chat.ts:64:20)
bolt-ai-dev-1  |     at async Object.callRouteAction (/app/node_modules/.pnpm/@remix-run+server-runtime@2.10.0_typescript@5.5.2/node_modules/@remix-run/server-runtime/dist/data.js:37:16)
bolt-ai-dev-1  |     at async /app/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:4612:21
bolt-ai-dev-1  |     at async callLoaderOrAction (/app/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:4677:16)
bolt-ai-dev-1  |     at async Promise.all (index 1)
bolt-ai-dev-1  |     at async callDataStrategyImpl (/app/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:4552:17)
bolt-ai-dev-1  |     at async callDataStrategy (/app/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:4041:19)
bolt-ai-dev-1  |     at async submit (/app/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:3900:21)
bolt-ai-dev-1  |     at async queryImpl (/app/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:3858:22)
bolt-ai-dev-1  |     at async Object.queryRoute (/app/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:3827:18)
bolt-ai-dev-1  |     at async handleResourceRequest (/app/node_modules/.pnpm/@remix-run+server-runtime@2.10.0_typescript@5.5.2/node_modules/@remix-run/server-runtime/dist/server.js:413:20)
bolt-ai-dev-1  |     at async requestHandler (/app/node_modules/.pnpm/@remix-run+server-runtime@2.10.0_typescript@5.5.2/node_modules/@remix-run/server-runtime/dist/server.js:156:18)
bolt-ai-dev-1  |     at async /app/node_modules/.pnpm/@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge/node_modules/@remix-run/dev/dist/vite/cloudflare-proxy-plugin.js:70:25 {
bolt-ai-dev-1  |   cause: undefined,
bolt-ai-dev-1  |   url: 'http://host.docker.internal:11434/api/chat',
bolt-ai-dev-1  |   requestBodyValues: {
bolt-ai-dev-1  |     format: undefined,
bolt-ai-dev-1  |     model: 'claude-3-5-sonnet-latest',
bolt-ai-dev-1  |     options: { num_ctx: 32768, num_predict: 8000, temperature: 0 },
bolt-ai-dev-1  |     messages: [ [Object], [Object] ],
bolt-ai-dev-1  |     tools: undefined
bolt-ai-dev-1  |   },
bolt-ai-dev-1  |   statusCode: 404,
bolt-ai-dev-1  |   responseHeaders: {
bolt-ai-dev-1  |     'content-length': '78',
bolt-ai-dev-1  |     'content-type': 'application/json; charset=utf-8',
bolt-ai-dev-1  |     date: 'Tue, 26 Nov 2024 23:57:05 GMT'
bolt-ai-dev-1  |   },
bolt-ai-dev-1  |   responseBody: '{"error":"model \\"claude-3-5-sonnet-latest\\" not found, try pulling it first"}',
bolt-ai-dev-1  |   isRetryable: false,
bolt-ai-dev-1  |   data: undefined,
bolt-ai-dev-1  |   [Symbol(vercel.ai.error)]: true,
bolt-ai-dev-1  |   [Symbol(vercel.ai.error.AI_APICallError)]: true
bolt-ai-dev-1  | }
```

in the web console on the network tab, I can't see any mention of Ollama, but I might just be looking for the wrong term? 
<img width="561" alt="image" src="https://github.com/user-attachments/assets/b6d119de-9372-481d-86dd-962a1da78437">

### Expected behavior

No error, just the three dots indicating the user the assistant is loading, and then build the output project, folders and files, ending up in the Preview tab working just fine. 

### Screen Recording / Screenshot

https://github.com/user-attachments/assets/f2ef35a1-503a-4576-9681-cd04d87eb865

### Platform

- OS: [e.g. **macOS**, Linux]
- Browser: [e.g. **Chrome**, **Safari**]

**- CPU/GPU: M1 Chip, 16 Go RAM** 

### Additional context

Also, I removed my OpenWebUI docker instance I had, that could sometimes cause some troubles whereas it's running on another port... (localhost:3000 by default. I'll try to run it from another computer that requires less VRAM and get the big models running on that chip) i.e, couldn't load both of them on the same computer.

Plus, I have specified in the Issue that Importing Folders worked, I feel like deploying another branch, like nightly or dev, be great not to mix them up. Mentioning the fresh install sounded right to me because the last few hours brought me new features I wasn't expecting that fast :)... but bringing me back to the issue I've had on Linux yesterday.

I tried to be as clear as possible. Feel free to ask more context, screenshots or screen recordings if needed. 

Keep up the good work!!
It is clear you guys are having a great time and that project is going places. 

Cheerz
guzz

**Comment by coleam00** [comment]
Hey Guzz, thanks for the detailed post and I appreciate your kind words for the project too!

First of all, yes we are thinking about how to best structure this repo to make it more mature, including having a dev/unstable branch and doing weekly releases to main. Still working through how to implement this the best so we don't hurt the dev experience.

For this error, this happens once and a while where you switch to Ollama but for some reason under the hood it tries to use Claude 3.5 Sonnet still (the default model). I've had this happen before and just restarting the container worked - this is an open issue to just figure out why it happens sometimes.

**Comment by alcclkl** [comment]
api\bolt.git\app\app\utils  constants.ts -->  export const DEFAULT_MODEL = 'OLLAMA MODEL NAME ';

LIKE THIS

export const DEFAULT_MODEL = 'gemma2:2b';
