### ISSUE TITLE
ollama model specification does not take effect

### ISSUE THREAD

**Issue by lostmaniac** [coleam00/bolt.new-any-llm#451]
### Describe the bug

APICallError [AI_APICallError]: Not Found
    at /data/bolt.new-any-llm/node_modules/.pnpm/@ai-sdk+provider-utils@1.0.20_zod@3.23.8/node_modules/@ai-sdk/provider-utils/dist/index.js:505:14
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async postToApi (/data/bolt.new-any-llm/node_modules/.pnpm/@ai-sdk+provider-utils@1.0.20_zod@3.23.8/node_modules/@ai-sdk/provider-utils/dist/index.js:398:28)
    at async OllamaChatLanguageModel.doStream (/data/bolt.new-any-llm/node_modules/.pnpm/ollama-ai-provider@0.15.2_zod@3.23.8/node_modules/ollama-ai-provider/dist/index.js:485:50)
    at async fn (file:///data/bolt.new-any-llm/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/dist/index.mjs:3938:23)
    at async file:///data/bolt.new-any-llm/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/dist/index.mjs:256:22
    at async _retryWithExponentialBackoff (file:///data/bolt.new-any-llm/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/dist/index.mjs:86:12)
    at async startStep (file:///data/bolt.new-any-llm/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/dist/index.mjs:3903:13)
    at async fn (file:///data/bolt.new-any-llm/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/dist/index.mjs:3977:11)
    at async file:///data/bolt.new-any-llm/node_modules/.pnpm/ai@3.4.9_react@18.3.1_sswr@2.1.0_svelte@4.2.18__svelte@4.2.18_vue@3.4.30_typescript@5.5.2__zod@3.23.8/node_modules/ai/dist/index.mjs:256:22
    at async chatAction (/data/bolt.new-any-llm/app/routes/api.chat.ts:64:20)
    at async Object.callRouteAction (/data/bolt.new-any-llm/node_modules/.pnpm/@remix-run+server-runtime@2.10.0_typescript@5.5.2/node_modules/@remix-run/server-runtime/dist/data.js:37:16)
    at async /data/bolt.new-any-llm/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:4612:21
    at async callLoaderOrAction (/data/bolt.new-any-llm/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:4677:16)
    at async Promise.all (index 1)
    at async callDataStrategyImpl (/data/bolt.new-any-llm/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:4552:17)
    at async callDataStrategy (/data/bolt.new-any-llm/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:4041:19)
    at async submit (/data/bolt.new-any-llm/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:3900:21)
    at async queryImpl (/data/bolt.new-any-llm/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:3858:22)
    at async Object.queryRoute (/data/bolt.new-any-llm/node_modules/.pnpm/@remix-run+router@1.17.0/node_modules/@remix-run/router/dist/router.cjs.js:3827:18)
    at async handleResourceRequest (/data/bolt.new-any-llm/node_modules/.pnpm/@remix-run+server-runtime@2.10.0_typescript@5.5.2/node_modules/@remix-run/server-runtime/dist/server.js:413:20)
    at async requestHandler (/data/bolt.new-any-llm/node_modules/.pnpm/@remix-run+server-runtime@2.10.0_typescript@5.5.2/node_modules/@remix-run/server-runtime/dist/server.js:156:18)
    at async /data/bolt.new-any-llm/node_modules/.pnpm/@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge/node_modules/@remix-run/dev/dist/vite/cloudflare-proxy-plugin.js:70:25 {
  cause: undefined,
  url: 'http://10.88.7.222:11434/api/chat',
  requestBodyValues: {
    format: undefined,
    model: 'claude-3-5-sonnet-latest',
    options: { num_ctx: 6144, num_predict: 8000, temperature: 0 },
    messages: [ [Object], [Object] ],
    tools: undefined
  },
  statusCode: 404,
  responseHeaders: {
    'content-length': '78',
    'content-type': 'application/json; charset=utf-8',
    date: 'Fri, 29 Nov 2024 09:15:26 GMT'
  },
  responseBody: '{"error":"model \\"claude-3-5-sonnet-latest\\" not found, try pulling it first"}',
  isRetryable: false,
  data: undefined,
  [Symbol(vercel.ai.error)]: true,
  [Symbol(vercel.ai.error.AI_APICallError)]: true

### Link to the Bolt URL that caused the error

10.88.7.222:11434

### Steps to reproduce

Use directly after startup

### Expected behavior

1

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by 7R4S3R** [comment]
go to your app/utils/constants.ts and open with notepad or any type of text editor. on the 9th line from the top of the code you will see this line: export const DEFAULT_MODEL = 'claude-3-5-sonnet-latest'; replace just the name of the ollama model you want to use and then save the file as all files. afterwards you should restart bolt and your ollama models should be there and you shouldnt get the error unknown.

**Comment by engmsilva** [comment]
I'm running Bolt on docker and I'm having the same problem. I installed the LLama model and it is listed in the Bolt frontend. So it's not through the bolt that selects the model? 

![image](https://github.com/user-attachments/assets/83bd2d4f-c376-4e4e-b001-dfd5ae0e3bb3)

**Comment by dustinwloring1988** [comment]
it should be fixed now

**Comment by coleam00** [comment]
Yes this is fixed now!
