### ISSUE TITLE
Just Updated the code and it looks like it broken now

### ISSUE THREAD

**Issue by skimtiyaz** [coleam00/bolt.new-any-llm#470]
### Describe the bug

Re-optimizing dependencies because lockfile has changed
  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
13:57:42 [vite] Pre-transform error: Failed to load url @radix-ui/react-tooltip (resolved id: @radix-ui/react-tooltip) in .../developement/bolt.new-any-llm/app/components/chat/BaseChat.tsx. Does the file exist?
13:57:43 [vite] Pre-transform error: Failed to load url @ai-sdk/cohere (resolved id: @ai-sdk/cohere) in .../developement/bolt.new-any-llm/app/lib/.server/llm/model.ts. Does the file exist?
13:57:43 [vite] Pre-transform error: Failed to load url @radix-ui/react-tooltip (resolved id: @radix-ui/react-tooltip) in .../developement/bolt.new-any-llm/app/components/chat/BaseChat.tsx. Does the file exist?
13:57:43 [vite] Pre-transform error: Failed to load url ignore (resolved id: ignore) in .../developement/bolt.new-any-llm/app/components/chat/ImportFolderButton.tsx. Does the file exist?
[unocss] failed to load icon "ph:folder-simple-upload"
13:57:45 [vite] Error when evaluating SSR module /app/lib/.server/llm/model.ts: failed to import "@ai-sdk/cohere"
|- Error: Cannot find module '@ai-sdk/cohere' imported from '.../developement/bolt.new-any-llm/app/lib/.server/llm/model.ts'
    at nodeImport (file:///.../developement/bolt.new-any-llm/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:53484:19)
    at ssrImport (file:///.../developement/bolt.new-any-llm/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:53349:22)
    at eval (.../developement/bolt.new-any-llm/app/lib/.server/llm/model.ts:13:38)
    at async instantiateModule (file:///.../developement/bolt.new-any-llm/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:53408:5)

13:57:45 [vite] Error when evaluating SSR module /app/lib/.server/llm/stream-text.ts: failed to import "@ai-sdk/cohere"
|- Error: Cannot find module '@ai-sdk/cohere' imported from '.../developement/bolt.new-any-llm/app/lib/.server/llm/model.ts'
    at nodeImport (file:///.../developement/bolt.new-any-llm/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:53484:19)
    at ssrImport (file:///.../developement/bolt.new-any-llm/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:53349:22)
    at eval (.../developement/bolt.new-any-llm/app/lib/.server/llm/model.ts:13:38)
    at async instantiateModule (file:///.../developement/bolt.new-any-llm/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:53408:5)

13:57:45 [vite] Error when evaluating SSR module /app/routes/api.enhancer.ts: failed to import "@ai-sdk/cohere"
|- Error: Cannot find module '@ai-sdk/cohere' imported from '.../developement/bolt.new-any-llm/app/lib/.server/llm/model.ts'
    at nodeImport (file:///.../developement/bolt.new-any-llm/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:53484:19)
    at ssrImport (file:///.../developement/bolt.new-any-llm/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:53349:22)
    at eval (.../developement/bolt.new-any-llm/app/lib/.server/llm/model.ts:13:38)
    at async instantiateModule (file:///.../developement/bolt.new-any-llm/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:53408:5)

13:57:45 [vite] Error when evaluating SSR module virtual:remix/server-build: failed to import "@ai-sdk/cohere"
|- Error: Cannot find module '@ai-sdk/cohere' imported from '.../developement/bolt.new-any-llm/app/lib/.server/llm/model.ts'
    at nodeImport (file:///.../developement/bolt.new-any-llm/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:53484:19)
    at ssrImport (file:///.../developement/bolt.new-any-llm/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:53349:22)
    at eval (.../developement/bolt.new-any-llm/app/lib/.server/llm/model.ts:13:38)
    at async instantiateModule (file:///.../developement/bolt.new-any-llm/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:53408:5)

13:57:45 [vite] Internal server error: Cannot find module '@ai-sdk/cohere' imported from '.../developement/bolt.new-any-llm/app/lib/.server/llm/model.ts'
      at nodeImport (file:///.../developement/bolt.new-any-llm/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:53484:19)
      at ssrImport (file:///.../developement/bolt.new-any-llm/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:53349:22)
      at eval (.../developement/bolt.new-any-llm/app/lib/.server/llm/model.ts:13:38)
      at async instantiateModule (file:///.../developement/bolt.new-any-llm/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:53408:5)
13:57:45 [vite] Internal server error: Cannot find module '@ai-sdk/cohere' imported from '.../developement/bolt.new-any-llm/app/lib/.server/llm/model.ts'
      at nodeImport (file:///.../developement/bolt.new-any-llm/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:53484:19)
      at ssrImport (file:///.../developement/bolt.new-any-llm/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:53349:22)
      at eval (.../developement/bolt.new-any-llm/app/lib/.server/llm/model.ts:13:38)
      at async instantiateModule (file:///.../developement/bolt.new-any-llm/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:53408:5) (x2)
13:57:45 [vite] Internal server error: Cannot find module '@ai-sdk/cohere' imported from '.../developement/bolt.new-any-llm/app/lib/.server/llm/model.ts'
      at nodeImport (file:///.../developement/bolt.new-any-llm/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:53484:19)
      at ssrImport (file:///.../developement/bolt.new-any-llm/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:53349:22)
      at eval (.../developement/bolt.new-any-llm/app/lib/.server/llm/model.ts:13:38)
      at async instantiateModule (file:///.../developement/bolt.new-any-llm/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:53408:5) (x3)

### Link to the Bolt URL that caused the error

https://github.com/coleam00/bolt.new-any-llm

### Steps to reproduce

just updated and relaunched it and got this error today

### Expected behavior

pasted the whole log in the bug description above

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by kekePower** [comment]
Sometimes an update necessitates installing new modules.

I.e. npm install

**Comment by aliasfoxkde** [comment]
Second that, clear the lock file and run `pnpm install` again.

**Comment by dfinley** [comment]
I'm also experiencing this exact issue when using docker and the development build.  Tho, I am not experiencing this issue when building with the production flags and docker.

**Comment by aliasfoxkde** [comment]
My bad, I'm not using Docker. I'm using straight `pnpm install` on Windows which seemed straight forward. Had auth issues on a second box (also Windows) and haven't tested on Linux yet. If you can, try the non-docker instructions? My trouble has been getting the damn Secrets (API Keys) to work in Cloudflare Pages.

**Comment by skimtiyaz** [comment]
### it was fixed by running the following commands:

- `cd path/to/your/repo`        # Navigate to your repo
- `git fetch`                  # Fetch latest changes
- `git checkout main`           # Switch to the main branch (or master)
- `git pull origin main`        # Pull latest changes from remote
- `pnpm install`                # Install new modules if needed
- `rm pnpm-lock.yaml`           # Clear lock file if necessary
- `pnpm install`                # Reinstall dependencies

**Comment by skimtiyaz** [comment]
### it was fixed by running the following commands:

- `cd path/to/your/repo`        # Navigate to your repo
- `git fetch`                  # Fetch latest changes
- `git checkout main`           # Switch to the main branch (or master)
- `git pull origin main`        # Pull latest changes from remote
- `pnpm install`                # Install new modules if needed
- `rm pnpm-lock.yaml`           # Clear lock file if necessary
- `pnpm install`                # Reinstall dependencies
