### ISSUE TITLE
err when run pnpm run dev

### ISSUE THREAD

**Issue by RonDragon** [coleam00/bolt.new-any-llm#527]
### Describe the bug

D:\Dev\bolt.new-any-llm>pnpm run dev

> bolt@ dev D:\Dev\bolt.new-any-llm
> remix vite:dev

 warn  Data fetching is changing to a single fetch in React Router v7
┃ You can use the `v3_singleFetch` future flag to opt-in early.
┃ -> https://remix.run/docs/en/2.13.1/start/future-flags#v3_singleFetch
┗
*** Received structured exception #0xc0000005: access violation; stack: 7fffc4052f57 7ff70d35251b 7ff70d3525e3 7ff70d2f3f9c 7ff70d2f3f47 7ff70cb6bf5e 7ff70cb6c26f 7ff70b951ed6 7ff70cc95e3f 7ff70cc9d0d6 7ff70cc96343 7ff70cc9d0d6 7ff70cc93cdc 7ff70b941e66 7ff70e4a572f 7fffdaf17373 7fffdbffcc90
MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
    at Miniflare2.#assembleAndUpdateConfig (D:\Dev\bolt.new-any-llm\node_modules\.pnpm\miniflare@3.20241106.1\node_modules\miniflare\src\index.ts:1404:10)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Mutex.runWith (D:\Dev\bolt.new-any-llm\node_modules\.pnpm\miniflare@3.20241106.1\node_modules\miniflare\src\workers\shared\sync.ts:66:45)
    at Miniflare2.#waitForReady (D:\Dev\bolt.new-any-llm\node_modules\.pnpm\miniflare@3.20241106.1\node_modules\miniflare\src\index.ts:1486:3)
    at Miniflare2._getProxyClient (D:\Dev\bolt.new-any-llm\node_modules\.pnpm\miniflare@3.20241106.1\node_modules\miniflare\src\index.ts:1692:3)
    at Miniflare2.getBindings (D:\Dev\bolt.new-any-llm\node_modules\.pnpm\miniflare@3.20241106.1\node_modules\miniflare\src\index.ts:1715:23)
    at getPlatformProxy (D:\Dev\bolt.new-any-llm\node_modules\.pnpm\wrangler@3.91.0_@cloudflare+workers-types@4.20241127.0\node_modules\wrangler\src\api\integrations\platform\index.ts:116:24)
    at configureServer (D:\Dev\bolt.new-any-llm\node_modules\.pnpm\@remix-run+dev@2.15.0_@remix-run+react@2.15.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_zyxju6yjkqxopc2lqyhhptpywm\node_modules\@remix-run\dev\dist\vite\cloudflare-proxy-plugin.js:55:11)
    at _createServer (file:///D:/Dev/bolt.new-any-llm/node_modules/.pnpm/vite@5.4.11_@types+node@22.10.1_sass-embedded@1.81.0_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:63080:20)
    at configResolved (D:\Dev\bolt.new-any-llm\node_modules\.pnpm\@remix-run+dev@2.15.0_@remix-run+react@2.15.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_zyxju6yjkqxopc2lqyhhptpywm\node_modules\@remix-run\dev\dist\vite\plugin.js:768:27)
    at async Promise.all (index 3)
    at resolveConfig (file:///D:/Dev/bolt.new-any-llm/node_modules/.pnpm/vite@5.4.11_@types+node@22.10.1_sass-embedded@1.81.0_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:66404:3)
    at _createServer (file:///D:/Dev/bolt.new-any-llm/node_modules/.pnpm/vite@5.4.11_@types+node@22.10.1_sass-embedded@1.81.0_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:62758:18)
    at dev (D:\Dev\bolt.new-any-llm\node_modules\.pnpm\@remix-run+dev@2.15.0_@remix-run+react@2.15.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_zyxju6yjkqxopc2lqyhhptpywm\node_modules\@remix-run\dev\dist\vite\dev.js:39:16)
    at Object.viteDev (D:\Dev\bolt.new-any-llm\node_modules\.pnpm\@remix-run+dev@2.15.0_@remix-run+react@2.15.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_zyxju6yjkqxopc2lqyhhptpywm\node_modules\@remix-run\dev\dist\cli\commands.js:221:3)
    at Object.run (D:\Dev\bolt.new-any-llm\node_modules\.pnpm\@remix-run+dev@2.15.0_@remix-run+react@2.15.0_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_zyxju6yjkqxopc2lqyhhptpywm\node_modules\@remix-run\dev\dist\cli\run.js:271:7) {
  code: 'ERR_RUNTIME_FAILURE',
  cause: undefined
}
 ELIFECYCLE  Command failed with exit code 1.

### Link to the Bolt URL that caused the error

r

### Steps to reproduce

1. i  run the command pnpm install
2. i run the command pnpm run dev
3. get the err

### Expected behavior

run the app

### Platform

- OS: [ Windows 10]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by dustinwloring1988** [comment]
Here are some ways to install it, use the first video (sorry no voice over or anything), you can compare your version of node to mine maybe using 'node --version'

**Comment by TrumanDu** [comment]
the same issue

**Comment by RonDragon** [comment]
I still get the same error with your version. I then tried to update all the versions to the latest and still got the same error.

**Comment by luizguil99** [comment]
to fix this you have to downgrade wrangler npm 
install wrangler@3.57.1
npm run dev

**Comment by RonDragon** [comment]
> to fix this you have to downgrade wrangler npm install wrangler@3.57.1 npm run dev

thanks that's work for me!

**Comment by dustinwloring1988** [comment]
@luizguil99 thanks for the help

**Comment by harellevy** [comment]
the right thing is to install Latest Microsoft Visual C++ Redistributable Version
