### ISSUE TITLE
bolt not building or running on Windows 11 (npm / pnpm)

### ISSUE THREAD

**Issue by harellevy** [coleam00/bolt.new-any-llm#544]
### Describe the bug

I'm getting this error
```
*** Received structured exception #0xc0000005: access violation; stack: 7ffbbf303007 7ff7b0002d2a 7ff7b0002df3 7ff7affa477c 7ff7affa4727 7ff7af81c73e 7ff7af81ca4f 7ff7ae601ed6 7ff7af94661f 7ff7af94d8b6 7ff7af946b23 7ff7af94d8b6 7ff7af9444bc 7ff7ae5f1e66 7ff7b115775f 7ffbd4ade8d6 7ffbd5b3fbcb
MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
    at Miniflare2.#assembleAndUpdateConfig (C:\Users\Harel\Documents\bolt-new\bolt.new-any-llm\node_modules\miniflare\src\index.ts:1404:10)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Mutex.runWith (C:\Users\Harel\Documents\bolt-new\bolt.new-any-llm\node_modules\miniflare\src\workers\shared\sync.ts:66:45)
    at Miniflare2.#waitForReady (C:\Users\Harel\Documents\bolt-new\bolt.new-any-llm\node_modules\miniflare\src\index.ts:1486:3)
    at Miniflare2._getProxyClient (C:\Users\Harel\Documents\bolt-new\bolt.new-any-llm\node_modules\miniflare\src\index.ts:1692:3)
    at Miniflare2.getBindings (C:\Users\Harel\Documents\bolt-new\bolt.new-any-llm\node_modules\miniflare\src\index.ts:1715:23)
    at getPlatformProxy (C:\Users\Harel\Documents\bolt-new\bolt.new-any-llm\node_modules\wrangler\wrangler-dist\cli.js:177937:20)
    at configureServer (C:\Users\Harel\Documents\bolt-new\bolt.new-any-llm\node_modules\@remix-run\dev\dist\vite\cloudflare-proxy-plugin.js:55:11)
    at _createServer (file:///C:/Users/Harel/Documents/bolt-new/bolt.new-any-llm/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:63080:20)
    at configResolved (C:\Users\Harel\Documents\bolt-new\bolt.new-any-llm\node_modules\@remix-run\dev\dist\vite\plugin.js:768:27)
```
Looks like a problem with miniflare lib, probably caused by a dependency called `wrangler` which uses it.

### Link to the Bolt URL that caused the error

pnpm run dev

### Steps to reproduce

1. download repo
2. pnpm install
3. edit env.local to this:
```
# Get your Anthropic API Key in your account settings -
# https://console.anthropic.com/settings/keys
# You only need this environment variable set if you want to use Claude models
ANTHROPIC_API_KEY=<your_api_key> # change your api key to key of ANTHROPIC api

# Include this environment variable if you want more logging for debugging locally
VITE_LOG_LEVEL=debug

# Example Context Values for qwen2.5-coder:32b
#
# DEFAULT_NUM_CTX=32768 # Consumes 36GB of VRAM
# DEFAULT_NUM_CTX=24576 # Consumes 32GB of VRAM
# DEFAULT_NUM_CTX=12288 # Consumes 26GB of VRAM
# DEFAULT_NUM_CTX=6144 # Consumes 24GB of VRAM
DEFAULT_NUM_CTX=5500
```
4. run `pnpm run dev`

I'm using Windows 11 and Node 18.18, also tried 20.17.

### Expected behavior

running / building / showing the right error if something is missing

### Screen Recording / Screenshot

![image](https://github.com/user-attachments/assets/6ac9544d-0934-40a2-9348-49304ce3a9c1)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by dustinwloring1988** [comment]
@harellevy does this PR fix your issue?

**Comment by harellevy** [comment]
Closing the issue
install Latest Microsoft Visual C++ Redistributable Version from https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170 if you have this issue.

**Comment by ppnine1234** [comment]
This solves the issue of running npm/pnpm and getting errors on both Windows 10 and Windows 11. It works perfectly. Thank you very much. 👍👍👍👍👍👍👍👍👍 ☺️☺️☺️☺️
