### ISSUE TITLE
error while selecting Ollama models

### ISSUE THREAD

**Issue by Arun4you** [coleam00/bolt.new-any-llm#619]
### Describe the bug

![Screenshot 2024-12-10 at 3 34 04 PM](https://github.com/user-attachments/assets/df79bda1-efc7-4d53-a845-b4ae1a6a4975)
![Screenshot 2024-12-10 at 3 34 33 PM](https://github.com/user-attachments/assets/65a46799-4079-4e39-b0b3-55d78a7afa54)
![Screenshot 2024-12-10 at 3 34 50 PM](https://github.com/user-attachments/assets/704d69ee-96f8-4f91-8c55-2a54beae19b2)

Ollama API running:
![Screenshot 2024-12-10 at 3 40 59 PM](https://github.com/user-attachments/assets/928eb31a-69bb-454e-849a-21c24a0c59b7)

Error when starting using "pnpm run dev":

arun_subramanian@Aruns-Mac-mini bolt.new-any-llm % pnpm run dev

> bolt@ dev /Users/arun_subramanian/Documents/ide/bolt.new-any-llm
> remix vite:dev

 warn  Route discovery/manifest behavior is changing in React Router v7
┃ You can use the `v3_lazyRouteDiscovery` future flag to opt-in early.
┃ -> https://remix.run/docs/en/2.13.1/start/future-flags#v3_lazyRouteDiscovery
┗
 warn  Data fetching is changing to a single fetch in React Router v7
┃ You can use the `v3_singleFetch` future flag to opt-in early.
┃ -> https://remix.run/docs/en/2.13.1/start/future-flags#v3_singleFetch
┗
  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
baseUrl:  http://localhost:11434
Error getting Ollama models: TypeError: fetch failed
    at node:internal/deps/undici/undici:12618:11
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.getOllamaModels [as getDynamicModels] (/Users/arun_subramanian/Documents/ide/bolt.new-any-llm/app/utils/constants.ts:368:22)
    at async Promise.all (index 0)
    at Module.initializeModelList (/Users/arun_subramanian/Documents/ide/bolt.new-any-llm/app/utils/constants.ts:457:9)
    at handleRequest (/Users/arun_subramanian/Documents/ide/bolt.new-any-llm/app/entry.server.tsx:30:3)
    at handleDocumentRequest (/Users/arun_subramanian/Documents/ide/bolt.new-any-llm/node_modules/.pnpm/@remix-run+server-runtime@2.15.0_typescript@5.7.2/node_modules/@remix-run/server-runtime/dist/server.js:340:12)
    at requestHandler (/Users/arun_subramanian/Documents/ide/bolt.new-any-llm/node_modules/.pnpm/@remix-run+server-runtime@2.15.0_typescript@5.7.2/node_modules/@remix-run/server-runtime/dist/server.js:160:18)
    at /Users/arun_subramanian/Documents/ide/bolt.new-any-llm/node_modules/.pnpm/@remix-run+dev@2.15.0_@remix-run+react@2.15.0_sass-embedded@1.81.0_typescript@5.7.2_vite@5.4.11_wrangler@3.91.0/node_modules/@remix-run/dev/dist/vite/cloudflare-proxy-plugin.js:70:25 {
  cause: Error: connect ECONNREFUSED ::1:11434
      at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
      at __node_internal_exceptionWithHostPort (node:internal/errors:671:12)
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:128:17) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 11434
  }
}

**claude-3-5-sonnet-latest is taken by default even Ollama model is selected.**

![Screenshot 2024-12-10 at 3 48 47 PM](https://github.com/user-attachments/assets/7efb99e2-ca18-4b6f-a883-2ff7a48db7b5)

![Screenshot 2024-12-10 at 3 49 09 PM](https://github.com/user-attachments/assets/7e9ee54c-124f-4b00-aa09-8e6c5f395239)

### Link to the Bolt URL that caused the error

https://github.com/coleam00/bolt.new-any-llm/blob/main/app/utils/constants.ts

### Steps to reproduce

Follow the setup instructions from the doc.

.env.local change.
DEFAULT_NUM_CTX=8000
OLLAMA_API_BASE_URL=http://localhost:11434

command:
pnpm run dev

### Expected behavior

We should be able to select Ollama models running locally.

### Platform

macOS

**Comment by Shivamjohri247** [comment]
same issue faced by me on windows env :/

**Comment by tzhf** [comment]
same here

**Comment by maczowow** [comment]
same here

**Comment by mfahad92** [comment]
I had similar issue, can you try replacing OLLAMA_API_BASE_URL value from http://localhost:11434 to http://127.0.0.1:11434 in .env.local

**Comment by Arun4you** [comment]
> I had similar issue, can you try replacing OLLAMA_API_BASE_URL value from http://localhost:11434 to http://127.0.0.1:11434 in .env.local?
> 
> ref: [nodejs/undici#1248](https://github.com/nodejs/undici/issues/1248)

This resolves the issue. Good to mention in the document.
