### ISSUE TITLE
pnpm run dev not working on windows

### ISSUE THREAD

**Issue by jagga2105** [coleam00/bolt.new-any-llm#88]
### Describe the bug

pnpm run dev

> bolt@ dev C:\Users\win10\Documents\bolt.new-any-llm
> remix vite:dev

*** Received structured exception #0xc0000005: access violation; stack: 7ffe5242258f 7ff6ff11337b 7ff6ff113443 
7ff6ff1074bc 7ff6ff107467 7ff6fe987d5e 7ff6fe98806f 7ff6fd871706 7ff6fd8714ea 7ff6feaff97f 7ff6feb06b36 7ff6feaffe9c 7ff6feb06b36 7ff6feafd80c 7ff6fd861551 7ff7001e8bff 7ffe712a7373 7ffe7253cc90
MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
    at #assembleAndUpdateConfig (C:\Users\win10\Documents\bolt.new-any-llm\node_modules\.pnpm\miniflare@3.20240701.0\node_modules\miniflare\dist\src\index.js:9178:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Mutex.runWith (C:\Users\win10\Documents\bolt.new-any-llm\node_modules\.pnpm\miniflare@3.20240701.0\node_modules\miniflare\dist\src\index.js:3521:16)
    at async #waitForReady (C:\Users\win10\Documents\bolt.new-any-llm\node_modules\.pnpm\miniflare@3.20240701.0\node_modules\miniflare\dist\src\index.js:9235:5)
    at async Miniflare2._getProxyClient (C:\Users\win10\Documents\bolt.new-any-llm\node_modules\.pnpm\miniflare@3.20240701.0\node_modules\miniflare\dist\src\index.js:9359:5)
    at async Miniflare2.getBindings (C:\Users\win10\Documents\bolt.new-any-llm\node_modules\.pnpm\miniflare@3.20240701.0\node_modules\miniflare\dist\src\index.js:9378:25)
    at async getPlatformProxy (C:\Users\win10\Documents\bolt.new-any-llm\node_modules\.pnpm\wrangler@3.63.2_@cloudflare+workers-types@4.20240620.0\node_modules\wrangler\wrangler-dist\cli.js:210522:20)   
    at async configureServer (C:\Users\win10\Documents\bolt.new-any-llm\node_modules\.pnpm\@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge\node_modules\@remix-run\dev\dist\vite\cloudflare-proxy-plugin.js:55:11)
    at async _createServer (file:///C:/Users/win10/Documents/personal/dash_tiny/bolt.new-any-llm/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:63299:20)   
    at async configResolved (C:\Users\win10\Documents\bolt.new-any-llm\node_modules\.pnpm\@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge\node_modules\@remix-run\dev\dist\vite\plugin.js:750:27)
    at async Promise.all (index 3)
    at async resolveConfig (file:///C:/Users/win10/Documents/personal/dash_tiny/bolt.new-any-llm/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:66626:3)    
    at async _createServer (file:///C:/Users/win10/Documents/personal/dash_tiny/bolt.new-any-llm/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.9_sass@1.77.6/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:62977:18)   
    at async dev (C:\Users\win10\Documents\bolt.new-any-llm\node_modules\.pnpm\@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge\node_modules\@remix-run\dev\dist\vite\dev.js:39:16)
    at async Object.viteDev (C:\Users\win10\Documents\bolt.new-any-llm\node_modules\.pnpm\@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge\node_modules\@remix-run\dev\dist\cli\commands.js:220:3)
    at async Object.run (C:\Users\win10\Documents\bolt.new-any-llm\node_modules\.pnpm\@remix-run+dev@2.10.0_@remix-run+react@2.10.2_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_qwyxqdhnwp3srgtibfrlais3ge\node_modules\@remix-run\dev\dist\cli\run.js:271:7) {
  code: 'ERR_RUNTIME_FAILURE',
  cause: undefined
}
 ELIFECYCLE  Command failed with exit code 1.

### Link to the Bolt URL that caused the error

N/A

### Steps to reproduce

1. Clone the repo
2. Install dependencies using **pnpm install**
3. Setup .env.local file
4. Run the project using **pnpm run dev**

### Expected behavior

The project should run properly

### Platform

- OS: Windows

### Additional context

I need help with this, can someone help me please.

**Comment by zaazo** [comment]
Yeah had the same problem I think it only works on linux for some reason

**Comment by zaazo** [comment]
FINALLY FOUND A SOLUTION WILL DOCUMENT IT AND SEND IT. @jagga2105

**Comment by jagga2105** [comment]
> FINALLY FOUND A SOLUTION WILL DOCUMENT IT AND SEND IT. @jagga2105 
Thanks @zaazo I will wait for the solution

**Comment by TinoJHB** [comment]
im using npm run dev and not pnpm on win... you do need to: npm install -g pnpm

**Comment by yffaffy** [comment]
I changed the wrangler version on line 108 in package.json to `"wrangler": "3.57.1"` to get around that error.

**Comment by yffaffy** [comment]
> I changed the wrangler version on line 108 in package.json to `"wrangler": "3.57.1"` to get around that error.

After looking into this a little more I was able to start the app with the latest version of wrangler after updating Visual Studio C++

https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by jagga2105** [comment]
@yffaffy Thanks, this solution worked perfectly. I will close this issue now.

**Comment by Kyrpel** [comment]
> FINALLY FOUND A SOLUTION WILL DOCUMENT IT AND SEND IT. @jagga2105

can you share also here, I have the same problem

**Comment by Kyrpel** [comment]
> Another person posted the solution 
> 
> After looking into this a little more I was able to start the app with the latest version of wrangler after updating Visual Studio C++
> 
> [https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170](https://www.linkedin.com/safety/go?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fcpp%2Fwindows%2Flatest-supported-vc-redist%3Fview%3Dmsvc-170&trk=flagship-messaging-web&messageThreadUrn=urn%3Ali%3AmessagingThread%3A2-ZTA3OTZmMzEtNWQ1Mi00ODNmLWJhNzItYTIzMTk0N2QyZDYzXzAxMA%3D%3D)

Thank you I have already updated my build tools, nothing changed for me.
